[feat]: rename weights optimisers
gchq/coreax pull request #449
Opened 2024-02-19 16:10 UTC by tc85324

### PR Type
Closes #448 
- Code style update (formatting, local variables)
- Refactoring (no functional changes)

### Does this PR introduce a breaking change?
- Any uses of `coreax.weights.MMD` will need to be replaced with `coreax.weights.MMDWeightsOptimiser`.
- Any uses of `coreax.weights.SBQ` will ned to be replaced with `coreax.weights.SBQWeightsOptimiser`.

### Checklist before requesting a review
- [x] I have made sure that my PR is not a duplicate.
- [x] My code follows the style guidelines of this project.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have performed a self-review of my code.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules.

2024-02-20 14:43 UTC, gchqdev227 requested changes
Overall this is a good change, but in order to fulfil our OSS obligations I would request that you add aliases for the `MMD` and `SBQ` classes. My suggestion would be to do something like:

```python
import warnings

class MMD(MMDWeightsOptimiser):

    def __init__(self, *args, **kwargs):
        warnings.warn("This class is now deprecated in favour of 'MMDWeightsOptimiser', and will be removed in version 0.3", category=DeprecationWarning)
        super().__init__(*args, **kwargs)
```
At some point we may wish to then to explicitly undocument these aliases, but for now it's not the end of the world if they make it in.

Also, please add an entry in the changlog!

2024-02-20 15:32 UTC, tc85324 commented
Added changelog and deprecation warnings as requested.

2024-02-22 14:15 UTC, gchqdev227 approved these changes
All looks good, thanks for sorting that!

2024-02-22 14:15 UTC, gchqdev227 commented on coreax/weights.py
> +@deprecated("Renamed to SBQWeightsOptimiser; will be removed in version 0.3.0")
Neat decorator use!!

2024-02-22 14:54 UTC, merged