Feature/validation removal
gchq/coreax pull request #473
Opened 2024-02-20 18:10 UTC by tc85324

### PR Type
Closes #462 #461 #460 #459 

- Feature
- Code style update (formatting, local variables)

### Description
Removes explicit validation checks and any consequently redundant tests. Moves `KeyArray`
 and `KeyArrayLike` into a new `custom_types` module.

### Does this PR introduce a breaking change?
Moving the types to a new module may be considered breaking. However, these are not really mean't for external use anyway.

### Checklist before requesting a review
- [ ] I have made sure that my PR is not a duplicate.
- [ ] My code follows the style guidelines of this project.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have performed a self-review of my code.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

2024-02-21 13:17 UTC, jd750687 commented
`coreax.validation` is still used in several locations. Is there a reason these have been left in?

2024-02-21 13:20 UTC, jd750687 requested changes
There are multiple public interfaces that take values from the user. They should have some level of checking to ensure that the correct values are being used or we protect code that uses unchecked values.

2024-02-21 13:23 UTC, jd750687 commented
@tp832944 What are your thoughts?

2024-02-21 13:32 UTC, tc85324 commented on coreax/coresubset.py
>          self.block_size = block_size
My understand was that we were no longer validating any rules which were logically inconsistent. I.E. no user should expect a negative block size to work/make sense?

2024-02-21 13:43 UTC, tc85324 commented on coreax/coresubset.py
>          self.block_size = block_size
If #427 is to be added, along with subsequent changes to type hinting, then most of the "validation" will come from type checking (which could be enforced at runtime if so desired)

2024-02-21 13:46 UTC, tc85324 commented on coreax/custom_types.py
This can be changed to whatever name is preferred. I chose `custom_types` as this indicates that the types aren't reexported types from another package, but indeed custom to this package.

2024-02-22 11:18 UTC, jd750687 commented
> > `coreax.validation` is still used in several locations. Is there a reason these have been left in?
> 
> Please can you indicate locations (I've just done a commit to remove some left over unused imports). If it is the uses in `approximation.py` then it is because they are addressed in a separate branch (which can either be pulled in here or left for a separate pull whichever is preferred)

They are all in `approximation.py`, so no issue there if it is covered by separate changes.

2024-03-19 06:48 UTC, closed without merging