Feature/restructure input validation 420
gchq/coreax pull request #479
Opened 2024-02-23 13:40 UTC by pc532627

### PR Type

- Feature

### Description

Input validation has been adjusted to adhere to new requirements. Note that several inputs are not validated at all now, and users could get errors that we do not control when using unexpected inputs.

### How Has This Been Tested?

All unit tests run and adjusted as needed.

### Does this PR introduce a breaking change?

N/A

### Checklist before requesting a review
- [x] I have made sure that my PR is not a duplicate.
- [x] My code follows the style guidelines of this project.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have performed a self-review of my code.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules.

2024-02-23 13:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/gchq/coreax?pullRequest=479) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/gchq/coreax?pullRequest=479) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: pc532627<br/>:x: sk062380<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/gchq/coreax?pullRequest=479) it.</sub>

2024-02-26 17:08 UTC, pc532627 commented
@gchqdev227 - Code updated inline with ideal input validation method, can you take a look when you get a chance?

2024-02-28 17:01 UTC, gchqdev227 requested changes
A couple *incredibly minor* gripes, but this is really good stuff!

2024-02-29 13:23 UTC, pc532627 commented on coreax/approximation.py
> +        # Randomly select training points
Removed

2024-02-29 13:24 UTC, pc532627 commented on coreax/approximation.py
> +            raise exception
I've removed the `exception` from the raise statements of this form - it has required me to disable some pylint checks, but if this leads to more accurate coverage assessments, I think it's worth it

2024-02-29 13:26 UTC, pc532627 commented on tests/unit/test_approximation.py
> +class InvalidKernel:
Thanks!

2024-02-29 14:41 UTC, pc532627 commented on coreax/approximation.py
> +            raise exception
@gchqdev227 I've updated the pyproject.toml with the suggested ignore from coverage, but it does not seem to actually exclude the raise lines. I've tried a few different variants and nothing seems to do the job. Am I missing something silly?

2024-02-29 14:59 UTC, pc532627 commented
Note - do not merge this branch into main until all input validation and import stye is finished

2024-03-05 10:13 UTC, gchqdev227 submitted a review, later dismissed
Looks good, thanks for making those changes!

2024-03-05 10:16 UTC, gchqdev227 commented on coreax/approximation.py
> +            raise exception
Ah, I thought it stripped whitespace before checking the regex but apparently not. I've had success with [this](https://github.com/gchq/ConcourseTools/blob/f4d53983a581268c8ca7448082317a22cf5ac2d2/pyproject.toml#L11) in the past, might be worth a go? If it does then please push and I'll re-approve, but if not then suggest we revisit in another branch.

2024-03-05 11:22 UTC, pc532627 commented on coreax/approximation.py
> +            raise exception
That's worked - thanks, it seems the whitespace was the issue, noted for the future.

2024-03-05 11:26 UTC, gchqdev227 approved these changes

2024-03-18 11:11 UTC, pc532627 commented
This now also closes #451 when merged into main.

2024-03-18 11:14 UTC, pc532627 commented
A couple of notes for review:

- The unittest workflows that uses the pinned package versions now fail due to JAX changing what type of error is raised in one case. Do we want to update these pinned versions, and should this be part of this PR?
- The import style can now be changed as needed, I expect this should be part of a different PR however as it would make this one quite large to review.

2024-03-19 12:49 UTC, jn177246 requested changes
One occurrence of `coreax.validation` found within codebase. Other than that, it looks good.

2024-03-19 12:49 UTC, jn177246 commented on tests/unit/test_coresubset.py
Within `test_greedy_body(self)` (line 341) `coreax.validation` is still called causing a unit test to fail.

2024-03-19 14:47 UTC, pc532627 commented on tests/unit/test_coresubset.py
Thanks for catching this - updated pushed to resolve

2024-03-22 11:10 UTC, jn177246 approved these changes
Looks good.

2024-03-22 11:18 UTC, merged