feat: bump support to include python 3.12
gchq/coreax pull request #556
Opened 2024-04-15 15:00 UTC by tc85324

Closes #555, closes #236

### PR Type

- Feature
- Build related changes
- CI related changes
- Documentation content changes

### Description
Bumps support to include python 3.12

### How Has This Been Tested?
All existing tests pass.

### Does this PR introduce a breaking change?
No

### Checklist before requesting a review
- [x] I have made sure that my PR is not a duplicate.
- [x] My code follows the style guidelines of this project.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have performed a self-review of my code.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules.

2024-04-16 14:42 UTC, tp832944 commented on .github/workflows/docs.yml
Update running on pinned package versions to 3.12 too.

2024-04-16 14:49 UTC, tp832944 requested changes
Thanks @tc85324. A few more updates please:

- Add this to the CHANGELOG.
- .github/workflows/pre_commit_checks.yml
- .github/workflows/pre_commit_checks.yml
- .readthedocs.yaml
- pyproject.toml
- README Python version badge

2024-04-16 20:28 UTC, tc85324 commented
The requested updates have been made, sorry for missing so many. The badge in the README is dynamically updated by PyPI, so the changes to the `pyproject.toml` should cover this.

2024-04-17 09:10 UTC, tp832944 approved these changes

2024-04-17 09:10 UTC, merged