feat: use composition for kernel approximation
gchq/coreax pull request #583
Opened 2024-04-26 14:41 UTC by tc85324

Closes #544, Closes #297

### PR Type

- Feature
- Code style update (formatting, local variables)
- Refactoring (no functional changes)
- Documentation content changes
- Tests

### Description
- Update `kernel.py` and `approximation.py` module docstrings
- Use `@override` to reduce docstring reuse
- Use `equinox.Module` for all `Kernel`s
- Remove now redundant approximator handling from `coresubset.py`, `kernel.py`, and `refine.py`
- Remove now redundant/incompatible tests from `test_refine.py`, `test_kernel.py`, `test_coresubset.py` and `test_approximation.py`
- Update `herding_approximate_gram_matrix.py` example
- Disable redundant/incompatible pylint `abstract-methods` rule
- Add ruff-pylint exception for `__check_init__` dunder method
- Fixes typo `_anchor_body` -> `_annchor_body`

### How Has This Been Tested?
All the tests pass.

### Does this PR introduce a breaking change?
Yes, the kernel approximation API has completely changed (there is no feasible deprecation strategy).

### Checklist before requesting a review
- [x] I have made sure that my PR is not a duplicate.
- [x] My code follows the style guidelines of this project.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have performed a self-review of my code.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules.

2024-04-30 13:58 UTC, pc532627 requested changes
Only very minor points. Looking at historic test workflows, as far as I can tell, there is no performance impact on the code

2024-04-30 14:54 UTC, tc85324 commented on coreax/approximation.py
> +The :class:`ApproximateKernel`\ s in this module provide the functionality required to
This provides a good explanation https://stackoverflow.com/a/23853904, there are other options but I had opted for this as it was the most concicse

2024-04-30 15:00 UTC, tc85324 commented on coreax/approximation.py
> +def _random_indices(
I wasn't going to document these as they are marked private (by the underscore), and their functionality is reasonably self descriptive, but will included if you think its important to have.

2024-04-30 15:00 UTC, tc85324 commented on coreax/approximation.py
> +    An kernel that requires the attributes for random regression.
Good spot!

2024-04-30 15:01 UTC, tc85324 commented on coreax/approximation.py
> +class RandomRegressionKernel(Kernel):
Correct, this is mean't to be abstract still, it allows an "abstract" type hierarchy

2024-04-30 15:02 UTC, tc85324 commented on coreax/approximation.py
> +        def _annchor_body(idx: int, features: Array) -> Array:
The JIT would have been redundant as it is only called by `fori_loop`, which is already compiling anyway

2024-04-30 15:02 UTC, tc85324 commented on coreax/coresubset.py
> +        iterative add points to the coreset balancing  selecting points in high density
Well spotted!

2024-04-30 15:03 UTC, tc85324 commented on coreax/coresubset.py
>      @staticmethod
The JIT is redundant as the function is only called by the `fori_loop`, which is already compiling anyway

2024-04-30 15:03 UTC, tc85324 commented on coreax/coresubset.py
>      @staticmethod
Same as the other responses

2024-04-30 15:06 UTC, tc85324 commented on coreax/kernel.py
> +which if parameterized with an ``output_scale`` of
I'm not sure what defines British English, but [OED has it with a 'z'](https://www.oed.com/dictionary/parameterize_v)

2024-04-30 16:08 UTC, pc532627 commented on coreax/approximation.py
> +The :class:`ApproximateKernel`\ s in this module provide the functionality required to
Thanks for the explanation - happy to keep it

2024-04-30 16:09 UTC, pc532627 commented on coreax/approximation.py
> +def _random_indices(
I think it is important to, please push updates for both

2024-04-30 16:09 UTC, pc532627 commented on coreax/approximation.py
> +def _random_regression(
I think it is important to, please push updates for both

2024-04-30 16:10 UTC, pc532627 commented on coreax/kernel.py
> +which if parameterized with an ``output_scale`` of
In this case lets leave it, sorry for the misflag!

2024-05-01 10:51 UTC, tc85324 commented
All issues should now be addressed. Additional changes have been made to allow for a successful merge. In particular, a test has been removed from Stein Thinning which cannot be made compatible with the new kernel design.

2024-05-02 08:25 UTC, pc532627 commented on coreax/approximation.py
> +        def _annchor_body(idx: int, features: Array) -> Array:
The entry `features` in the docstring needs updating to `_features`

2024-05-02 08:27 UTC, pc532627 requested changes
Only one tiny change - otherwise all looks good @tc85324

2024-05-02 08:28 UTC, pc532627 commented on coreax/approximation.py
> +        def _annchor_body(idx: int, features: Array) -> Array:
@tc85324  just for reference this is the single change needed

2024-05-02 09:02 UTC, merged