Check kernel params, extend kernel test coverage
gchq/coreax pull request #722
Opened 2024-08-02 15:57 UTC by db091756

### PR Type

- Feature
- Tests

### Description

Added `__init_check__`'s to every kernel in `scalar_valued.py`.

### How Has This Been Tested?

Added additional tests to expand coverage.

### Does this PR introduce a breaking change?

(Write your answer here.)

### Screenshots

(Write your answer here.)

### Checklist before requesting a review
- [ ] I have made sure that my PR is not a duplicate.
- [ ] My code follows the style guidelines of this project.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have performed a self-review of my code.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

2024-08-05 10:01 UTC, rg936672 requested changes
Main comments: add any restrictions to docstrings, and test for error messages, not just error types.

Other comments:
 - If an invalid kernel type is passed to a UniCompositeKernel, it should throw a `TypeError` rather than a `ValueError`.

2024-08-05 15:58 UTC, db091756 commented on tests/unit/test_kernels.py
> +            SteinKernel(base_kernel="base_kernel", score_function=jnp.negative)
This makes the line too long

2024-08-06 08:52 UTC, rg936672 commented on coreax/kernels/scalar_valued.py
> +        a positive
```suggestion
        positive
```

2024-08-06 08:52 UTC, rg936672 commented on coreax/kernels/scalar_valued.py
> +        squared exponential kernel. Must be non-negative.
```suggestion
        squared exponential kernel. Must be non-negative
```

2024-08-06 08:52 UTC, rg936672 commented on tests/unit/test_kernels.py
> +        with pytest.raises(ValueError):
This should also be done on any other `with pytest.raises` usages in this file.

2024-08-06 08:53 UTC, rg936672 commented on tests/unit/test_kernels.py
> +            SteinKernel(base_kernel="base_kernel", score_function=jnp.negative)
```suggestion
            SteinKernel(
                base_kernel="base_kernel",  # pyright: ignore[reportArgumentType]
                score_function=jnp.negative,
            )
```

2024-08-06 08:54 UTC, rg936672 requested changes
Almost there - a couple of minor formatting changes, and some more `match=` in `with pytest.raises` blocks.

2024-08-06 11:28 UTC, rg936672 requested changes
Just a few remaining missed `with pytest.raises` that don't check error messages, then we should be done

2024-08-06 11:28 UTC, rg936672 commented on tests/unit/test_kernels.py
> +            with pytest.raises(ValueError):
check error messages for all of these also

2024-08-06 11:28 UTC, rg936672 commented on tests/unit/test_kernels.py
> +        with pytest.raises(TypeError):
Check error message here

2024-08-06 13:38 UTC, db091756 commented
> Looks good! Approved assuming all the CI passes.
Got there in the end!

2024-08-06 13:38 UTC, merged