Performance testing CI workflow
gchq/coreax pull request #738
Opened 2024-08-16 08:52 UTC by rg936672

### PR Type

- CI related changes

### Description

Add a CI workflow for performance testing: 

 * On each push to `main`, it records a set of performance metrics.
 * On each push to a PR, it computes performance metrics and compares them the most recent recorded set of performance metrics from `main`, and then adds a comment to the PR with a summary of any significant differences.

Also makes a couple of changes to `jit_test`:
 * Adds an optional normalisation factor, which is used to reduce variance from running the performance tests across different machines.
 * `JITCompilableFunction`s now have an optional string name (and are named "Function 1", "Function 2", etc if `None` is given).

### How Has This Been Tested?

See usage at https://github.com/rg936672/coreax/pull/1 and https://gist.github.com/rg936672/094213d70dcc9c03ec49a81545627373.

### Does this PR introduce a breaking change?

No.

### Screenshots

(Write your answer here.)

### Checklist before requesting a review
- [ ] I have made sure that my PR is not a duplicate.
- [ ] My code follows the style guidelines of this project.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have performed a self-review of my code.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

2024-08-16 09:05 UTC, rg936672 commented
Things we'll want to add to this in future:
 - More performance tests
 - Recording performance data from PRs, so that performance can be compared both against the most recent `main` and against the most recent known data for the PR

2024-08-19 10:40 UTC, db091756 commented on coreax/util.py
> +    _name: Optional[str] = None,  # UNUSED
Rather than noting this as unused, could we just do `del _name` and include a comment explaining why this parameter is necessary here

2024-08-19 10:45 UTC, db091756 commented on tests/performance/__init__.py
> +"""Module containing tests for performance (i.e. speed) of the package."""
This and other new files needs copyright message

2024-08-19 10:46 UTC, db091756 commented on tests/performance/cases/basic_coresets.py
> +CORESET_SIZE = 100
I think I would be in favour of putting `num_data_points` and `num_features` as global constants here as well, as this will have an effect on runtime

2024-08-19 10:47 UTC, db091756 commented on tests/performance/compare.py
> +    """Extract the date from a performance data file name."""
Would be useful to have params and return in the docstring here

2024-08-19 10:48 UTC, db091756 commented on tests/performance/compare.py
> +) -> Dict[str, Dict[str, float]]:
Would be useful to have params and return in the docstring here

2024-08-19 10:48 UTC, db091756 commented on tests/performance/compare.py
> +    """Format the performance data for a specific test in a human-readable form."""
Would be useful to have params and return in the docstring here

2024-08-19 10:49 UTC, db091756 commented on tests/performance/compare.py
> +        inf
Would be useful to have params and return in the docstring here

2024-08-19 10:49 UTC, db091756 commented on tests/performance/compare.py
> +) -> List[Tuple[str, List[str]]]:
Would be useful to have params and return in the docstring here

2024-08-19 11:00 UTC, db091756 requested changes
I am happy with the code. But I think it would help future readers of the code to have more explanation in the docstrings. 

I also think it would be a nice QoL feature to include the `units` in the output. I.e. tell us somewhere the length of time each unit actually is. This way we can figure out how long it took to compute the coresets if we wanted to

2024-08-19 12:56 UTC, rg936672 commented
> I also think it would be a nice QoL feature to include the `units` in the output. I.e. tell us somewhere the length of time each unit actually is. This way we can figure out how long it took to compute the coresets if we wanted to

This will require a bit of finagling, as well as for more data to be stored in the gist. I'll give it a go though, as I agree it would be nice!

2024-08-19 14:04 UTC, db091756 commented
> > I also think it would be a nice QoL feature to include the `units` in the output. I.e. tell us somewhere the length of time each unit actually is. This way we can figure out how long it took to compute the coresets if we wanted to
> 
> This will require a bit of finagling, as well as for more data to be stored in the gist. I'll give it a go though, as I agree it would be nice!

I am happy to review this without this extra feature, and add it as a new issue

2024-08-19 14:53 UTC, rg936672 commented
> I am happy to review this without this extra feature, and add it as a new issue

As this will require changing the format of stored data, I'd prefer to get this right first time rather than splitting this!

2024-08-20 08:24 UTC, rg936672 commented
No clue why pre-commit is failing here; I can't reproduce the issue locally.

2024-08-20 13:43 UTC, db091756 commented
@rg936672 Is it possible to have a shared normalisation across the compilation and execution time?

2024-08-20 13:47 UTC, rg936672 commented
> @rg936672 Is it possible to have a shared normalisation across the compilation and execution time? As it is it may be slightly confusing as they both refer to the same `units`

It's certainly _possible_, but I don't think it'd be a good idea - execution is going to be very parallelisable and thus the time will be highly dependent on the number of cores available, whereas I would assume that compilation will be much less so, so depending on the hardware the two might vary independently. 

I can easily change the language on the comment though - how about just referring to them as "compilation units" and "execution units", or even "c-units" and "e-units"?

2024-08-20 13:56 UTC, db091756 commented
> > @rg936672 Is it possible to have a shared normalisation across the compilation and execution time? As it is it may be slightly confusing as they both refer to the same `units`
> 
> It's certainly _possible_, but I don't think it'd be a good idea - execution is going to be very parallelisable and thus the time will be highly dependent on the number of cores available, whereas I would assume that compilation will be much less so, so depending on the hardware the two might vary independently.
> 
> I can easily change the language on the comment though - how about just referring to them as "compilation units" and "execution units", or even "c-units" and "e-units"?

I would be happy with either, up to you!

2024-08-21 16:11 UTC, db091756 approved these changes

2024-08-21 16:11 UTC, merged