feat: fixed pyright complaints with SilentTQDM and made not printing default behaviour
gchq/coreax pull request #761
Opened 2024-08-30 10:31 UTC by db091756

…default behaviour

### PR Type

- Feature

### Description

Fixed pyright complaints with SilentTQDM and made not printing default behaviour

### How Has This Been Tested?

All tests pass.

### Does this PR introduce a breaking change?

(Write your answer here.)

### Screenshots

(Write your answer here.)

### Checklist before requesting a review
- [ ] I have made sure that my PR is not a duplicate.
- [ ] My code follows the style guidelines of this project.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have performed a self-review of my code.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

2024-08-30 15:05 UTC, tp832944 commented
This is worth adding to the changelog, so please do.

2024-08-30 15:09 UTC, tp832944 requested changes

2024-08-30 15:09 UTC, tp832944 commented on documentation/source/conf.py
> +    ("py:obj", "coreax.solvers.coresubset._SupervisedData"),
Duplicates line above.

2024-08-30 15:09 UTC, tp832944 commented on coreax/score_matching.py
> +        print_progress_bar: bool = False,
Remove `print_`.

2024-08-30 15:24 UTC, db091756 commented on coreax/util.py
> +        del args, kwargs
This just fixes the pyright complaints, happy to remove this line. They are not errors just warnings

2024-08-30 15:26 UTC, db091756 commented on coreax/score_matching.py
> +from tqdm import tqdm as LoudTQDM  # noqa:N812
We seem to use the codes throughout the codebase for the `noqa`s. Testing using the the name doesn't seem to work weirdly

2024-09-03 14:49 UTC, tp832944 commented on coreax/score_matching.py
> +from tqdm import tqdm as LoudTQDM  # noqa:N812
It looks like Ruff needs codes rather than names, so my suggestion is no good.

2024-09-03 14:52 UTC, tp832944 commented on coreax/util.py
> +        del args, kwargs
Pyright runs cleanly for me.

2024-09-03 14:55 UTC, db091756 commented on coreax/util.py
> +        del args, kwargs
Yeah they are not errors, just warnings

2024-09-03 14:59 UTC, db091756 commented on coreax/util.py
> +        del args, kwargs
We seem to delete unused `kwargs` elsewhere in the codebase e.g. in `metrics.py` and `approximation.py`

2024-09-03 15:06 UTC, tp832944 requested changes

2024-09-03 15:06 UTC, tp832944 commented on CHANGELOG.md
> +disable tqdm progress bar terminal output. Defaults to `` :data:`False` ``.
This doesn't define what `False` means. Also don't try to create Intersphinx links here - just clutter.

```suggestion
disable tqdm progress bar terminal output. Defaults to disabled (`False`).
```

2024-09-03 15:06 UTC, tp832944 commented on coreax/util.py
> +        del args, kwargs
No warnings either for me.

2024-09-03 15:09 UTC, db091756 commented on coreax/util.py
> +        del args, kwargs
Do you see anything like the above pic?

2024-09-03 15:27 UTC, tp832944 commented on coreax/util.py
> +        del args, kwargs
Nothing in PyCharm.

2024-09-03 15:29 UTC, tp832944 approved these changes

2024-09-03 15:46 UTC, merged