feat: added cubature recombination example.
gchq/coreax pull request #798
Opened 2024-10-02 15:08 UTC by tc85324

Closes #778

### PR Type
- Feature
- Tests

### Description
Adds a test to demonstrate the end-to-end usage of `TreeRecombination`
for constructing non-product cubature formulae from product cubature
formulae. A corresponding integration test has also been added for this
new example.

### How Has This Been Tested?
The new tests pass locally and contain theoretically grounded assertions.

### Does this PR introduce a breaking No

### Checklist before requesting a review
- [x] I have made sure that my PR is not a duplicate.
- [x] My code follows the style guidelines of this project.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have performed a self-review of my code.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules.

2024-10-09 16:20 UTC, pc532627 requested changes
A few documentation comments - additionally the doc builds fail - this might be resolved simply by merging in main to this branch

2024-10-09 16:20 UTC, pc532627 commented on examples/cubature_recombination.py
> +    :param monomial_powers:
I think this has not been filled in before committing but should be

2024-10-09 16:20 UTC, pc532627 commented on examples/cubature_recombination.py
> +    :return:
I think this has not been filled in before committing but should be

2024-10-09 16:20 UTC, pc532627 commented on examples/cubature_recombination.py
> +    Generates the
I think this has not been filled in before committing but should be

2024-10-09 16:20 UTC, pc532627 commented on examples/cubature_recombination.py
> +    Generates the
Can you add some mathematical background on the problem we are trying to solve here when updating?

2024-10-09 16:31 UTC, pc532627 commented
@tc85324 Related to end-to-end usage of recombination, I'd be interested in your thoughts on how to sensibly include Recombination into the benchmarking currently being done on PR #802 . In that PR, @qh681248  is exploring how the various coreset methods compare in terms of run-time and error (MMD, KSD, ...) on a suite of candidate test problems. Since recombination isn't an `ExplicitSizeSolver` direct comparisons to coresets from other methods of a given size may not be in some sense fair. We could exclude it from benchmarking because of this - but if you have any ideas on sensible ways to include it we'd be open to suggestions.

2024-10-18 06:27 UTC, tc85324 reviewed
> @tc85324 Related to end-to-end usage of recombination, I'd be interested in your thoughts on how to sensibly include Recombination into the benchmarking currently being done on PR #802 . In that PR, @qh681248  is exploring how the various coreset methods compare in terms of run-time and error (MMD, KSD, ...) on a suite of candidate test problems. Since recombination isn't an `ExplicitSizeSolver` direct comparisons to coresets from other methods of a given size may not be in some sense fair. We could exclude it from benchmarking because of this - but if you have any ideas on sensible ways to include it we'd be open to suggestions.  

Thank you for the review! Regarding benchmarking, I would say that the example in this pull is probably the canonical use case for recombination and it would be useful to have runtime performance figures for varying numbers of test-functions (dimension and degree), and in the case of `TreeRecombination`, `tree_reduction_factor`. While this won't be comparible to the `ExplicitSizeSolvers` it is useful from an implementaiton perspective as we can check/see if real world performance scales at the same/simlar rates to those claimed in the literature.

2024-10-18 09:05 UTC, pc532627 approved these changes

2024-10-18 09:07 UTC, merged