fix: numerical errors in GPU recombination
gchq/coreax pull request #874
Opened 2024-11-20 11:57 UTC by rg936672

### PR Type

- Bugfix
- Feature
- Code style update (formatting, local variables)
- Refactoring (no functional changes)
- Build related changes
- CI related changes
- Documentation content changes
- Tests

### Description

Closes #853. Not 100% sure on the validity of this fix, but the tests still all pass, and the correction applied at each iteration is on the order of 1e-7 (which is approximately the resolution of single-precision floating-point numbers around 1).

### How Has This Been Tested?

Existing tests pass as expected, even on a GPU machine. The correction applied each iteration is extremely minor.

### Does this PR introduce a breaking change?

An extra field has been added to `_EliminationState`. (This is private, though, so shouldn't be breaking?)

### Checklist before requesting a review
- [x] I have made sure that my PR is not a duplicate.
- [x] My code follows the style guidelines of this project.
- [x] I have ensured my code is easy to understand, including docstrings and comments where necessary.
- [x] I have performed a self-review of my code.
- [x] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I have updated CHANGELOG.md, if appropriate.

2024-11-25 09:44 UTC, tp832944 commented
> Should this PR also resolve #852? Additionally, would it be possible to add a GPU runner to the CI tests so we can avoid these issues going silently unnoticed in the future (will need to open a new issue for this)?

We had thought about this previously, but decided against it primarily on cost grounds. We do run GPU tests manually just before each release. A few older GPU bugs may have gone unnoticed until now because of a configuration issue with the GPU.

2024-11-27 12:25 UTC, tc85324 requested changes
I think your idea is good, and a valid approach! However, I believe we can achieve the same thing (fixing both #853 and #854) by simply correcting the following line, which is currently incorrect:
```python
# Old (incorrect)
updated_null_space_basis.at  = updated_null_space_basis.at[basis_index].set(0)
# New (correct)
updated_null_space_basis.at  = updated_null_space_basis.at[:, elimination_index].set(0)
```
In my own local tests, this appears to work on CPU and GPU devices; all tests pass on CPU and GPU devices.

The only other thing that might be worthwhile is to indicate to users (via the docstring or a warning) that enabling double precision ("jax_enable_x64") is sometimes required to obtain correct results.

2024-11-27 16:40 UTC, rg936672 commented
Ah, that does make sense - I'd just assumed the code was correct as I wasn't super familiar with the algorithm!

2024-11-28 00:24 UTC, tc85324 requested changes
Very small comment on updating the CHANGELOG, but otherwise looks good to me!

2024-11-28 00:24 UTC, tc85324 commented on CHANGELOG.md
> +- CaratheodoryRecombination now generates correct coresets on GPU machines
Should this now be updated to mention the fix for all the recombination solvers, and should there be links to the underlying issues (in addition to the existing PR link)? 
Maybe something like:
```
Corrected an implementation error in `coreax.solvers.CaratheodoryRecombination`
which caused numerical instability when using either `CaratheodoryRecombination`
or `TreeRecombination` on GPU machines. 
(#852, #853, #874)
```

2024-11-29 09:07 UTC, tc85324 approved these changes

2024-11-29 09:08 UTC, merged