Fail coverage workflow if coverage reduces
gchq/coreax pull request #891
Opened 2024-12-12 14:21 UTC by tp832944

closes: #890

### PR Type

- CI related changes

### Description

Use similar approach to performance workflow. Coverage badge does not retain sufficient precision so create a new history of coverage data.

### How Has This Been Tested?

Existing tests pass as expected.

Temporarily commit a large code file to reduce the coverage.

### Does this PR introduce a breaking change?

No

### Checklist before requesting a review
- [ ] I have made sure that my PR is not a duplicate.
- [ ] My code follows the style guidelines of this project.
- [ ] I have ensured my code is easy to understand, including docstrings and comments where necessary.
- [ ] I have performed a self-review of my code.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I have updated CHANGELOG.md, if appropriate.

2024-12-12 16:03 UTC, rg936672 requested changes
Looks good! A couple minor changes, mainly some missed "performance file" mentions that weren't converted over.

2024-12-12 16:03 UTC, rg936672 commented on tests/coverage/compare.py
> +    :param path: The path to the performance data file. Only the filename component
```suggestion
    :param path: The path to the coverage data file. Only the filename component
```

2024-12-13 09:39 UTC, tp832944 commented
You will see that the coverage is reporting a slight increase. This is because I set the 95.0% manually to seed the system for testing.

2024-12-13 16:28 UTC, rg936672 approved these changes

2024-12-13 16:35 UTC, merged