feat: Initial implementation of video benchmark
gchq/coreax pull request #893
Opened 2024-12-13 14:50 UTC by qh681248

#892

### PR Type

- Bugfix
- Feature
- Code style update (formatting, local variables)
- Refactoring (no functional changes)
- Build related changes
- CI related changes
- Documentation content changes
- Tests

### Description

### How Has This Been Tested?

Existing tests pass as expected.

New tests introduced with this change verify that...

### Does this PR introduce a breaking change?

### Checklist before requesting a review
- [ ] I have made sure that my PR is not a duplicate.
- [ ] My code follows the style guidelines of this project.
- [ ] I have ensured my code is easy to understand, including docstrings and comments where necessary.
- [ ] I have performed a self-review of my code.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I have updated CHANGELOG.md, if appropriate.

2024-12-18 10:05 UTC, bk958178 requested changes
Thanks @qh681248. Some minor questions and requested changes below

2024-12-19 13:46 UTC, qh681248 commented on benchmark/mnist_benchmark.py
> +            coreset_size=_size, kernel=stein_kernel, regularise=False
I have rerun MNIST benchmark, and while I was rerunning it anyway, I also changes some of the hyperparameters for MNIST benchmark.

2024-12-19 15:17 UTC, qh681248 commented on benchmark/pounce_benchmark.py
> +    raw_data = np.asarray(image_data)
Yes, it needs to be jnp.asarray for it to be used for coreset algorithm but it needs to be np.asarray for us to save frames later as gif, I have added 
 ` data = Data(jnp.array(umap_data))`

2024-12-19 15:18 UTC, qh681248 commented on benchmark/pounce_benchmark.py
> +    umap_model = umap.UMAP(densmap=True, n_components=25)
`n_components=25` was in the original pounce example script, it was chosen here for consistency

2024-12-19 16:18 UTC, bk958178 approved these changes
Thanks @qh681248. LGTM. Approving and merging

2024-12-19 16:25 UTC, merged