Present benchmarking results on documentation with images and gifs
gchq/coreax pull request #908
Opened 2024-12-24 11:27 UTC by qh681248

### PR Type

- Documentation content changes

### Description

Present the results of benchmarking in documentation.

### How Has This Been Tested?

Existing tests pass as expected.

No new tests were introduced
### Does this PR introduce a breaking change?

### Checklist before requesting a review
- [x] I have made sure that my PR is not a duplicate.
- [x] My code follows the style guidelines of this project.
- [x] I have ensured my code is easy to understand, including docstrings and comments where necessary.
- [x] I have performed a self-review of my code.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I have updated CHANGELOG.md, if appropriate.

2024-12-24 12:21 UTC, qh681248 commented
This is a copy of PR #900, the PR had to be closed due to git LFS migrate command closing the PR, please refer to that PR for comments.

2024-12-24 15:55 UTC, tp832944 requested changes
Some comments on here. Some are on #900 - look for unresolved comments.

2024-12-24 15:55 UTC, tp832944 commented on benchmark/pounce_benchmark.py
> +                    relative to the script's location.
Please use a single indent on any continuation line. If you try to align to the start of the line above, something inevitably ends up misaligned when something is renamed later.

2024-12-24 15:55 UTC, tp832944 commented on documentation/source/benchmark.rst
> +   density preserving :class:`~umap.umap_.UMAP` is applied to project the 28x28 images into 16 components
Overfull line.

2024-12-24 15:55 UTC, tp832944 commented on documentation/source/benchmark.rst
> +(60,000 training images) was 97.31%, serving as a baseline for evaluating the performance
Overfull line.

2024-12-24 15:55 UTC, tp832944 commented on documentation/source/benchmark.rst
> +     - 0.000977
This is the best instead of 0.001582.

2024-12-24 15:55 UTC, tp832944 commented on documentation/source/benchmark.rst
> +   on an **Amazon g4dn.12xlarge instance** with 4 NVIDIA T4 Tensor Core GPUs, 48 vCPUs,
Not just `Amazon`. Either `AWS EC2` or `Amazon Web Services EC2`.

2024-12-24 15:55 UTC, tp832944 commented on documentation/source/benchmark.rst
> +   5 random seeds and the metrics are averaged.
is repeated 5 times with a different random seed each time and the metrics...

2024-12-24 15:59 UTC, tp832944 commented on documentation/source/benchmark.rst
> +- Plots showing the accuracy (with error bars) of the MLP's predictions on the test set,
This bullet point is silly. Remove it and dedent all the remaining lines in this section.

2024-12-24 16:05 UTC, tp832944 commented on benchmark/mnist_benchmark_coresets_only.py
> +    # pylint: disable=R0801
Disable `duplicate-code` instead of `R0801`.

2024-12-24 16:09 UTC, tp832944 commented on benchmark/mnist_benchmark_coresets_only.py
> +    # pylint: disable=R0801
Add corresponding pylint enable.

2024-12-24 16:42 UTC, qh681248 commented on documentation/source/benchmark.rst
> +     - 0.000977
Cheers :)

2025-01-02 15:32 UTC, tp832944 requested changes
One pair of comments still outstanding on #900.

2025-01-03 14:38 UTC, tp832944 approved these changes

2025-01-03 14:39 UTC, merged